<script>
	import ons from 'onsenui';
	import { onMount } from 'svelte';
	import { Page, Button, ListItem, LazyList } from '$svelte-onsenui';
	import MyToolbar from './MyToolbar.svelte';

	var length = 5;				// length is the number of items in your data
	let children = [];		// children is an array generated by LazyList containing the indexes of items to be displayed

	let timer
	onMount(() => {
		if (!timer) timer = setInterval(()=>{}, 1000);
		return () => {
			if (timer) clearInterval(timer);
			timer = null;
		}
	})
</script>

<Page>
	<MyToolbar title='LazyList' />
	<div style="margin:50px">
		<Button on:click={() => length = 10}>  Change Length 10</Button>
		<Button on:click={() => length = 50}>  Change Length 50</Button>
		<Button on:click={() => length = 1000}>Change Length 1000</Button>
		<p>Showing {length} items</p>
	</div>

	<!-- Note that LazyList must be a direct descendant of a Page element -->
	<LazyList bind:children={children} {length} calculateItemHeight={() => ons.platform.isAndroid() ? 76 : 45} >
		<div slot='header'>header</div>
		{#each children as idx}
			<ListItem>{'Item ' + (idx + 1)}</ListItem>
		{/each}
		<div slot='footer'>footer</div>
	</LazyList>
</Page>
